version: '3.8'

services:
  fast-app:
    build:
      context: ./backend
      dockerfile: Dockerfile.fast

    container_name: fast-app
    ports:
      - "8001:8001"
    env_file:
      - backend/.env
    networks:
      - monitoring
      

  flask-app:
    build:
      context: ./backend
      dockerfile: Dockerfile.flask

    container_name: flask-app
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    networks:
      - monitoring


  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile

  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - flask-app
  #   networks:
  #     - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - fast-app
      - flask-app


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3333:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring


volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge